version: '3'
services:
  registration-service:
      build:
        context: ./server/registration-service
      ports:
        - "8761:8761"
      expose:
        - "8761"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
        interval: 10s
        retries: 2

  config-service:
    build:
      context: ./server/config-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - DISCOVERY_SERVICE_URI=http://registration-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      retries: 2
    depends_on:
      registration-service:
        condition: service_healthy

  proxy-service:
    build:
      context: ./server/proxy-service
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - DISCOVERY_SERVICE_URI=http://registration-service:8761/eureka
      - CONFIG_SERVICE_URI=http://config-service:8888
    depends_on:
      registration-service:
        condition: service_healthy
      config-service:
        condition: service_healthy

  todolist-service:
    build:
      context: ./server/todolist-service
    ports:
      - "8001:8001"
    expose:
      - "8001"
    environment:
      - DISCOVERY_SERVICE_URI=http://registration-service:8761/eureka
      - CONFIG_SERVICE_URI=http://config-service:8888
    depends_on:
      config-service:
        condition: service_healthy

  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "4200:4200"
  #   expose:
  #     - "4200"
  #   depends_on:
  #     config-service:
  #       condition: service_healthy
