version: '3'
services:
  registry-service:
      build:
        context: ./server/registry-service
      ports:
        - "8761:8761"
      expose:
        - "8761"
      healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761:actuator/health"]
      interval: 5s
      retries: 3

  config-service:
    build:
      context: ./server/config-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - DISCOVERY_SERVICE_URI=http://registry-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888:actuator/health"]
      interval: 5s
      retries: 3
    depends_on:
      registry-service:
        condition: service_healthy

  # proxy-service:
  #   build:
  #     context: ./server/proxy-service
  #   ports:
  #     - "8000:8000"
  #   expose:
  #     - "8000"
  #   depends_on:
  #     - config-service
  #     - registry-service

  todolist-service:
    build:
      context: ./server/todolist-service
    ports:
      - "8001:8001"
    expose:
      - "8001"
    environment:
      - DISCOVERY_SERVICE_URI=http://registry-service:8761/eureka
      - CONFIG_SERVICE_URI=http://config-service:8888
    depends_on:
      config-service:
        condition: service_healthy

  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "4200:4200"
